[package]
name = "keyboard-audio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mki = "0.2.3"
rand = "0.8.5"
rodio = "0.17.3"
thiserror = "1.0.52"
